version: '3'
name: booking
services:
  booking_dev:
    image: mysql:8.0
    restart: always

    environment:
      - MYSQL_USER=nakkim
      - MYSQL_PASSWORD=nakkim@test
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - LANG=C.UTF-8

    ports:
      - 5001:3306

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  booking_redis:
    image: redis:6.0.9
    restart: always

    ports:
      - 6379:6379
